name: Elijah Hampton
description: Personal website
menu:
 - page: Notes and Writing
   links:
    - title: "Cryptography"
    - url: "#cryptography" 
menu_external:
 - title: Email
   url: "https://elijahhamptonj@proton.me"
 - title: Github
   url: "https://www.github.com/elijahhampton"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: elijahhampton.github.io
locale: en_GB
