# Site name and description
name: Elijah Hampton
description: Personal website

# Menu configuration
menu:
 - page: Notes and Writing
   links:
    - title: "Cryptography"
      url: "/cryptography" 
menu_external:
 - title: Github
   url: "https://www.github.com/elijahhampton"

# Build settings
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: 
locale: en_GB

# Define default layouts
defaults:
  - 
    scope:
      path: "notes/cryptography"
    values:
      layout: "post"